// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD0twDVcflnAZn9wYsZi1eRe17qJochCQs',
//     appId: '1:692491609414:web:ff5b5846ebf38c93b3b147',
//     messagingSenderId: '692491609414',
//     projectId: 'trust-id-4dd68',
//     authDomain: 'trust-id-4dd68.firebaseapp.com',
//     storageBucket: 'trust-id-4dd68.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCrPgAgorkIJHiS6Igl1WGCHrGQJrLFYu4',
//     appId: '1:692491609414:android:b651f209faaf712fb3b147',
//     messagingSenderId: '692491609414',
//     projectId: 'trust-id-4dd68',
//     storageBucket: 'trust-id-4dd68.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBs6Y_gsmqWVpyNM903ydR98Hgz1DAHjS0',
//     appId: '1:692491609414:ios:89ab443ddc4f691cb3b147',
//     messagingSenderId: '692491609414',
//     projectId: 'trust-id-4dd68',
//     storageBucket: 'trust-id-4dd68.firebasestorage.app',
//     iosBundleId: 'com.example.trustid',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBs6Y_gsmqWVpyNM903ydR98Hgz1DAHjS0',
//     appId: '1:692491609414:ios:89ab443ddc4f691cb3b147',
//     messagingSenderId: '692491609414',
//     projectId: 'trust-id-4dd68',
//     storageBucket: 'trust-id-4dd68.firebasestorage.app',
//     iosBundleId: 'com.example.trustid',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD0twDVcflnAZn9wYsZi1eRe17qJochCQs',
//     appId: '1:692491609414:web:0d6de7aa326f89afb3b147',
//     messagingSenderId: '692491609414',
//     projectId: 'trust-id-4dd68',
//     authDomain: 'trust-id-4dd68.firebaseapp.com',
//     storageBucket: 'trust-id-4dd68.firebasestorage.app',
//   );
// }
